openapi: 3.0.0
info:
  title: 백엔드 API
  version: 1.0.0
  description: 백엔드 API 문서
paths:
  /:
    get:
      summary: Hello World
      responses:
        "200":
          description: 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
  /users:
    post:
      summary: 회원가입
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "201":
          description: 회원가입 성공
        "400":
          description: 이메일 중복 또는 유효하지 않은 요청
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
  /users/login:
    post:
      summary: 로그인
      description: 사용자 아이디와 비밀번호로 로그인합니다.
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "200":
          description: 로그인 성공
        "400":
          description: 로그인 실패 (잘못된 아이디 또는 비밀번호)
          content:
            application/json:
              schema: